### ISSUE TITLE
Address pandas warnings in order to use pandas 1.0...at which point they become fails

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#149]
Pandas 1.0 is released and that means it is time to address the pesky pandas warnings...because in 1.0 they are now fatal errors!

**Comment by kulshresthaa** [comment]
@e-lo How did you test the pandas 1.0 errors? Just run `roadway`, `transit` etc tests?
I upgraded pandas to 1.0 on my machine, do I need to update the requirements (or some other place) to use 1.0 version in wrangler?

**Comment by e-lo** [comment]
Yes, I ran the tests. 

It is basically all the warnings you get in previous versions of pandas that have been translated to errors.

If you are using a virtual environment to test wrangler you'll need to upgrade it there.

**Comment by e-lo** [comment]
@kulshresthaa I forgot to check in on this yesterday. Are you able to take this on so we can upgrade to pandas 1.0?

**Comment by kulshresthaa** [comment]
I forgot about this. I had started looking into it but never finished. I will work on it!

**Comment by kulshresthaa** [comment]
All `roadway` tests are passing except [this](https://github.com/wsp-sag/network_wrangler/blob/develop/tests/test_roadway.py#L314) one because of missing "ref" field in the [create_dummy_connector_links](https://github.com/wsp-sag/network_wrangler/blob/develop/network_wrangler/roadwaynetwork.py#L1683) which doesn't exist (I think) in small test network. 

Also, can you upgrade to pandas 1.0 and confirm that all `roadway` tests are passing at your end?

**Comment by kulshresthaa** [comment]
I am still not fixing any pandas warning, just the errors :)

**Comment by e-lo** [comment]
Fixed.
