### ISSUE TITLE
create_scenario is very slow

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/network_wrangler#163]
@e-lo, create_scenario is very slow to load even one project card on the full network. @DavidOry asked me to to ask you to investigate this slowdown. We can discuss on our call next week.

**Comment by e-lo** [comment]
is this still an issue?

**Comment by jhelsel11** [comment]
It is for the full base network. Dave asked me to add it when I was trying to do some bug fixing with him while sharing a screen.

**Comment by e-lo** [comment]
Can you send me the debug log which should LMK where it is getting hung up?

**Comment by jhelsel11** [comment]
Is this what you're looking for?

[network_standard_test.log](https://github.com/wsp-sag/network_wrangler/files/4412123/network_standard_test.log)

**Comment by e-lo** [comment]
Ah yes, this is happening at the read level for the highway network.
1.  I think we will make fast=True the default for large networks because that reduces the time significantly as well as not reading the shapes by default
2. We should think about doing this issue if that doesn't help enough
https://github.com/wsp-sag/network_wrangler/issues/43

**Comment by jhelsel11** [comment]
@DavidOry, thoughts?

**Comment by e-lo** [comment]
I'm working on a commit that will do #1...should be ready this afternoon if I have time to test

**Comment by jhelsel11** [comment]
@e-lo, I just ran create_base_scenario on the entire network, it took 13 minutes. create_scenario took less than a second after that.

**Comment by e-lo** [comment]
what about create project (which is what rachel was running)

**Comment by jhelsel11** [comment]
15 minutes. (Full network, no transit.)
