### ISSUE TITLE
Inconsistency b/w links and shapes

### ISSUE THREAD

**Issue by kulshresthaa** [wsp-sag/network_wrangler#176]
roadway links (`links_df`) and shapes (`shapes_df`) aren't consistent with each after a project card is applied. (https://github.com/wsp-sag/Lasso/issues/70)

**Comment by kulshresthaa** [comment]
@e-lo Let me know if you'd like to discuss this. 

For `roadway property change` project cards, links and shapes will be consistent but not for any other kind of project card (`add new roadway`, `roadway deletion`, and `parallel managed lanes`). 

Links has geometry which is stick b/w first and last node. Shapes define the true shape along that link. 

For deletion: we can modify the `shapes_df` to drop the links that are deleted. 

For addition: we don't define the geometry of new links in the project card, so those new added links will have missing geometry and location references in `links_df` and then `shapes_df` isn't also modified to add those new links.

For parallel managed lanes: When we create a parallel ml link from mainline link, we get the new geometry (ML_A and ML_B points) by offsetting the mainline A and B by delta. We also update `shapes_df` when creating managed lane network (not when applying the ML project card, because at that point we are only adding the ML attributes to mainline link). So in this case, we do have geometry of ML link in `shapes_df` and that will be stick link (probably best we can do) but then we have missing id's (`shstGeometryId` etc.) for those as we only construct new `model_link_id` for those links but not any other ids.

**Comment by e-lo** [comment]
@kulshresthaa 

I made new issues #179 and #180 for add/delete.

For ML, I'm not sure how we can create an entry in shapes table if it doesn't have a shape_id? My suggestion would be to add a similar scalar offset...does that make sense?

**Comment by e-lo** [comment]
Based on our meeting today, I think you should add some code in [this part of the `create_managed_lanes_network()`](https://github.com/wsp-sag/network_wrangler/blob/a91939ff8b1344b0c2080429b59bbd4f97caf9ed/network_wrangler/RoadwayNetwork.py#L1803) method to do the following:

- [ ] Create a geometry id based on shared streets methodology. See #180 for thoughts on this.  
- [ ] Add that geometry id to the appropriate field in the new links `links_df` records 
- [ ] Add that geometry id as the unique identifier in the shapes_df

Since all of this is similar to what happens for #180 (adding a link), you might want to encapsulate all these steps in a method two.

**Comment by kulshresthaa** [comment]
all of this is complete as part of separate issues for add/delete/managed lanes.
