### ISSUE TITLE
Should we allow new roadway nodes to be automatically re-numbered

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#193]
Picking up a previous discussion and per Rachel's request. If the options are:

(a) The user has to create log files in Cube using the same node numbering schema, but can then compare networks across scenarios directly, or;

(b) The user can create log files in Cube re-using the same nodes for different projects and then Wrangler takes care of the problem by sorting out the differences, which makes comparing networks across scenarios more difficult.

Rachel prefers (b). @e-lo: has this been implemented and then deprecated? I recall we discussed both approaches and settled on (a). Can we move to (b) and/or have an option?

**Comment by e-lo** [comment]
> The user can create log files in Cube re-using the same nodes for different projects and then Wrangler takes care of the problem by sorting out the differences, which makes comparing networks across scenarios more difficult.

We hadn't implemented this because of the **makes comparing networks across scenarios impossible** part -  which was what I thought we had discussed with Rachel and agreed to approach (a)?

Approach B would be do-able but not (in my opinion) very useful.  

The one difficult decision is what to do if you have nodes that wrangler has created, and then a project card that is directly specifying those nodes.  You would have to either decide to throw out all comparability of. the node #s after the base-base network OR know every project card in advance.

**Comment by e-lo** [comment]
Per discussions with @RachelWikenMC and @JonathanEhrlichMC,  we will pursue creation of a node (and link?) registry within a project card registry.   

I wrote up:
1. [issue in Lasso for creating such a registry](https://github.com/wsp-sag/Lasso/issues/96) 
2. #194 method for validating project card nodes based on registry nodes.  
3. [ issue in Lasso for running the project card node validation method on project creation and adding registry as a parameter ](https://github.com/wsp-sag/Lasso/issues/97)

**Comment by e-lo** [comment]
Closing this since it is now represented in other issues.
