### ISSUE TITLE
[FEATURE] Tag links/nodes/lines with applied projects

### ISSUE THREAD

**Issue by lmz** [wsp-sag/network_wrangler#282]
### User Story
*As a modeler who is building networks, I'd like to be able to see which links/nodes/lines have been modified by which project card*.  This would be helpful for QAing networks and debugging where changes came from.

We do this with NetworkWrangler 1.0 for roadways and have found it incredibly useful -- it's just a column with the project strings, comma-delimited.  We didn't do it for transit lines because we didn't have the standard network concept, but it would be useful to do so. 

I don't know if this is already implemented; I didn't see it if so...  Do you know, @i-am-sijia , @e-lo ?

### Priority 
High

### Level of Effort
Low (I am guessing?)

### Resolution Ideas
I'm not sure how to identify project cards; I suppose via the name as described in the project card but those can be long?  The filenames can also be long.  It may be necessary to create a short project card ID?

### Project
*Is there a funder or project associated with this feature?*
Yes, MTC.  Also I would be happy to implement.

### Who should be involved?
Implementer: 
Commenters: 
Users: 
Reviewers: 

### Risk
*Will this potentially break anything?*
I think this is low risk.

#### Tests
The apply project tests could be updated to verify the tagging has been applied.

**Comment by RachelWikenMC** [comment]
Adding my +1 - this would be super helpful to speed up network review , making sure cards applied correctly

**Comment by e-lo** [comment]
Suggested remedy for v1.0:

1. `projects` as a list of strings to `links_df` data model; appending a project name to selected links when they are `changed` or `added`. NOTE: this wouldn't tag "deleted links". 
2. `projects` as a list of strings to `nodes_df` data model; appending a project name to selected links when they are `changed` or `added`
3. `projects` as a list of strings to transit `trips` data model; appending a project name to selected trips when they are changed or added. Since trips is the unit that we currently operate on for transit I think this is ok.

NOTE: this wouldn't tag deleted entities.

Does this sound like a good plan @RachelWikenMC @lmz @i-am-sijia ?
