### ISSUE TITLE
[FEATURE] Put logs in their own file

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#287]
### User Story
*As a model user, I'd like to have my log files live with the output data files and be separated by info and debug rather than having them clutter my base directory.*

### Priority 
Low

### Level of Effort
Low

### Resolution Ideas
Many are already in "changes from MTC" branch.  

Reviewers: @lmz (b/c she is the logging 👑 )

### Risk
Low

#### Tests
General

**Comment by lmz** [comment]
My preference is for the logs to live alongside their output data files rather than in a specific fixed directory.  (e.g. see #286 ) For example, when we build our networks, I like to have the output folder structure look like this:
- network_PBA50_v02
  - 2015 = folder with 2015 networks
  - 2019 = folder with 2019 networks
  - 2022 = folder with 2019 networks
  - 2025 = folder with 2019 networks
  - (etc through horizon year)
  - network_build_20220401_1015_INFO.log = this includes a list of each project applied before each write; this file can be consulted to answer "what projects were included in the year XXXX network", etc.
  - network_build_20220401_1015_DEBUG.log = this includes debug details from the network building process, including validation issues that don't cause a hard failure in the network building process, but modelers might want to be aware of as a possible issue

So the location and name of the log is at the discretion of the script or notebook that created the log, but I tend to think they're most useful when sitting with the output for future forensic purposes.

**Comment by e-lo** [comment]
Addressed in merged PR
