### ISSUE TITLE
Runtime increase when applying project cards

### ISSUE THREAD

**Issue by yueshuaing** [wsp-sag/network_wrangler#363]
We observed a significant increase in runtime when applying project cards. Previously, it took about 30 minutes to apply all project cards in [BaseCorrections](https://github.com/Metropolitan-Council/project_card_registry/tree/Test1/projects/BaseCorrections) using the old NW, but now it takes 120 minutes in new NW. We found two potential reasons after a brief review of the code:

1. Performing validation checks each time a new change is applied.
2. The get_selection() method is taking longer to select links.

**Comment by e-lo** [comment]
@yueshuaing what is the test that you are running/process so that I can recreate or ascertain where the run time is going.  I admit that it is a little strange since when each individual selection is performed and each individual project card is applied my benchmarks showed a significant increase but I wonder if something changes when the sizes change or when it is repeated a bunch (i.e. we are caching too much in memory and it is memory swapping)

**Comment by yueshuaing** [comment]
I'm running the Metcouncil notebook createV01_standardnetwork, where it creates a scenario and apply all project cards in [BaseCorrections](https://github.com/Metropolitan-Council/project_card_registry/tree/Test1/projects/BaseCorrections). There are 71 project cards inside the folder.

version_00c_scenario = create_scenario(
base_scenario=version_00b_scenario,
project_card_filepath = project_card_dir
)
version_00c_scenario.apply_all_projects()

**Comment by e-lo** [comment]
Ok - so I profiled a bunch of the tests and  7 of 8 seconds of apply roadway feature change was validating results.  Addressing now...

**Comment by e-lo** [comment]
This should be complete - at least for this round with #378.

**Comment by yueshuaing** [comment]
I wanted to follow up on this issue. The runtime has improved compared to the previous version. In the MetCouncil workflow, applying all base year project cards used to take around 120 minutes, but it now takes 30 minutes. However, it’s still not as fast as expected (the runtime is similar to the old Network Wrangler). I noticed that during the application of project cards, the selection process takes a few seconds before moving to the next card. Could caching the selections potentially increase runtime?

**Comment by e-lo** [comment]
Caching shouldn't increase time - it should actually improve it compared to not caching so we don't select multiple times.

Can you take a a look at a profile  (`prof/test_<testname>`) for the full MetCouncil workflow or attach it for a pertinent test so I can review what might be going on? Or you can look at it yourself using [snakeviz](https://jiffyclub.github.io/snakeviz/)

Its kind of odd that any selection for just an ID would take much time at all so I'm wondering what is going on.  

It might also be that after the selection the deepcopy processes that happen are taking a long time for the full network - that would at least explain the difference between what you are seeing w.r.t. performance and what I see since the network is much larger.

**Comment by e-lo** [comment]
Also just to clarify - is it transit selection or roadway selection or both?

**Comment by yueshuaing** [comment]
> Also just to clarify - is it transit selection or roadway selection or both?

Thanks, I'll try when I complete testing all Metcouncil workflows.
I only noticed it in roadway for now. We don't have many transit project cards, so test applying transit project cards is pretty fast.
