### ISSUE TITLE
[BUG] Lost RoadLinksAttrs, RoadNodesAttrs and RoadShapesAttrs during the workflow

### ISSUE THREAD

**Issue by yueshuaing** [wsp-sag/network_wrangler#383]
## Describe the bug
In PR https://github.com/wsp-sag/network_wrangler/pull/379, new attributes—`RoadLinksAttrs`, `RoadNodesAttrs`, and `RoadShapesAttrs`—were introduced and are referenced in several locations, e.g., [class LinkOfTypeAccessor](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/network_wrangler/roadway/links/df_accessors.py#L60-L75). 
In the MetCouncil workflow, after loading the standard networks into a scenario, various procedures are applied to the roadway network (e.g., calculating the number of lanes, assigning groups, roadway classes, and adding rail links/nodes). After these preprocessing steps, project cards are applied, and standard networks are written out. However, during this preprocess, the information stored in RoadLinksAttrs, RoadNodesAttrs, and RoadShapesAttrs is lost, leaving them as empty dictionaries. This leads to errors when these attributes are accessed again.
For example:
```python
try:
    links_df.attrs["name"] == "road_links"
```

### Thoughts on resolution
Can we reset `RoadLinksAttrs`, `RoadNodesAttrs`, and `RoadShapesAttrs` to their default values if they are found to be empty during attribute checks. Alternatively, we could use the .get() method to provide a default value of None when the attributes are missing or empty, as shown below:
```python
links_df.attrs.get("name", None)  == "road_links"
```

**Comment by e-lo** [comment]
@yueshuaing - you need to create a test that shows if/where/how the `attrs` are getting dropped. They shouldn't be and need to be kept with the DF for other things to work well as well.   None of the current tests that I've run have shown the `attrs` getting dropped as of today so we need to figure out what is going on here rather than paper over it.  I can't do that without you creating a test or describing the exact situation where `attrs` are dropped. 

My first inclination is to guess that you are using `copy` instead of `copy.links_df.deepcopy()`? or using `pd.concat()` instead of `wr.concat_with_attr()`?

**Comment by yueshuaing** [comment]
It's the data merge and concatenation process causes the issue, which drops the attributes. I’ve fixed this in the MetCouncil Wrangler and Cube Wrangler. Also noticed the roadway wrangler card also triggers this issue. so I’ve made modifications there as well. I'll go ahead and close this issue.
