### ISSUE TITLE
Consider Flattening JSON to Pandas dataframe

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#41]
can use `json_flatten` to read, but to write will have to do [something fancier. ](https://stackoverflow.com/questions/23576869/pandas-convert-dataframe-to-nested-json)

As discussed: in PR https://github.com/wsp-sag/network_wrangler/pull/36

**Comment by josiekre** [comment]
I'm having a hard time following the conversation in the PR. What do you want to convert to a Pandas dataframe that is not already? 

Based on my limited understanding scanning the code, I'm guessing this issue is in reference to storing the Project Card selection criteria as a Pandas dataframe rather than dict?

**Comment by e-lo** [comment]
ProjectCard is being stored as a dict. Not sure now why we would need this but it could have been in reference to RoadwayNetwork or another class. I'm going to remove it from this sprint as it isn't needed for it.

**Comment by e-lo** [comment]
outdated
