### ISSUE TITLE
Add TransitNetwork method to adjust route shapes

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#62]
Should be able to implement the Project Card developed for #60 which would move routes to other facilities and change the stop pattern.

**Comment by josiekre** [comment]
Next steps:

- [ ] Build graph (depend on RoadwayNetwork) - load lazily as needed
- [ ] Write method to rebuild `shape.txt` to list *all* links traversed along graph (some links might be missing currently)

**Comment by josiekre** [comment]
Partridge takes the somewhat weird GTFS format for `shapes.txt` and converts each `shape_id` to a LINESTRING.

```
In [10]: net.feed.shapes
Out[10]:
   shape_id                                           geometry
0    160001  LINESTRING (-93.08546700000001 44.947709, -93....
1    160003  LINESTRING (-93.182079 44.959013, -93.182288 4...
2    210002  LINESTRING (-93.29700699999999 44.948366, -93....
3    210005  LINESTRING (-93.085111 44.95018, -93.085474 44...
4   2620002  LINESTRING (-93.184425 45.144458, -93.18444000...
..      ...                                                ...
58   830002  LINESTRING (-93.140535 44.91367, -93.140575 44...
59  8600005  LINESTRING (-93.34517 45.187116, -93.343475 45...
60   940001  LINESTRING (-93.085111 44.95018, -93.085474 44...
61   940002  LINESTRING (-93.085111 44.95018, -93.085474 44...
62   940004  LINESTRING (-93.27529100000001 44.981062, -93....
```

Because Partridge does this conversion, the LINK_ID, ShStRefId, etc get dropped. So we need to do something custom here anyway. What do you think of having a different file with the network-based graph data per route in it? We need to do something custom apart from Partridge anyway, and creating a different file might mitigate any future confusion. (cc: @e-lo @i-am-sijia @DavidOry)

**Comment by josiekre** [comment]
I looks like I can turn off the `GeoDataFrame` conversion by using a default Partridge config over the default Partridge `geo_config()`. I'm going to try that.

**Comment by josiekre** [comment]
Things to discuss as a team:

- [ ] ID differences for links and nodes between transit and roadway

**Comment by josiekre** [comment]
Details for "Use of shapes.txt for graph information":

One shape ID looks like this...

```
     shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence LINK_ID
7338   210005     44.950180    -93.085111              20002  337079
7339   210005     44.950558    -93.085474              20003  337079
7340   210005     44.950786    -93.085689              20004   15113
7341   210005     44.950862    -93.085784              20005   15113
7342   210005     44.950895    -93.085844              20006   15113
...       ...           ...           ...                ...     ...
7713   210005     44.949190    -93.294652             850003  414161
7714   210005     44.949240    -93.295298             850004  414161
7715   210005     44.949249    -93.295596             850005  414161
7716   210005     44.949249    -93.295596             860001  414161
7717   210005     44.949253    -93.295726             860002  413811
```

From Cube, we ideally want to pass nodes IDs into project cards, not link IDs (first or second node ID?).

**Comment by josiekre** [comment]
Can Cube give me link IDs rather than node IDs? Thoughts on why to add to discussion:

```
# Example project card
facility:
  trip_id: 14944022-JUN19-MVS-BUS-Weekday-01
properties:
  - property: shapes
    set: [1924, 1925, 1930]

# In Python, I need to convert these node IDs to link IDs to be able to edit shape.txt
In [113]: links[links['B'].isin(properties['set'])][['LINK_ID', 'B']]
Out[113]:
       LINK_ID     B
8171    428785  1924
8172    428786  1924
8173    428787  1924
8174    428788  1924
8175    428789  1925
8176    428790  1925
8177    428791  1925
8178    428792  1925
8179    428809  1930
8180    428810  1930
8181    428811  1930
8182    428812  1930
46631   712099  1925
46632   712100  1925
46633   712101  1925
46634   712108  1930
46635   712109  1930
46636   712110  1930

In [114]: links[links['A'].isin(properties['set'])][['LINK_ID', 'A']]
Out[114]:
       LINK_ID     A
8510    440875  1924
8511    440876  1924
8512    440877  1924
8513    440878  1924
8514    440879  1925
8515    440880  1925
8516    440881  1925
8517    440882  1925
8518    440899  1930
8519    440900  1930
8520    440901  1930
8521    440902  1930
46818   713561  1925
46819   713562  1925
46820   713563  1925
46821   713570  1930
46822   713571  1930
46823   713572  1930
```

We cannot tell which links yet, so we have to actually graph them.

```
In [121]:  nx.shortest_path(transit_net.graph, properties['set'])
---------------------------------------------------------------------------
NodeNotFound                              Traceback (most recent call last)
<ipython-input-121-f216e194aed1> in <module>
----> 1 nx.shortest_path(transit_net.graph, properties['set'])

/usr/local/Caskroom/miniconda/base/envs/metcouncil-netwrang/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/generic.py in shortest_path(G, source, target, weight, method)
    158             # Find paths to all nodes accessible from the source.
    159             if method == 'unweighted':
--> 160                 paths = nx.single_source_shortest_path(G, source)
    161             elif method == 'dijkstra':
    162                 paths = nx.single_source_dijkstra_path(G, source,

/usr/local/Caskroom/miniconda/base/envs/metcouncil-netwrang/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py in single_source_shortest_path(G, source, cutoff)
    333     """
    334     if source not in G:
--> 335         raise nx.NodeNotFound("Source {} not in G".format(source))
    336
    337     def join(p1, p2):

NodeNotFound: Source [1924, 1925, 1930] not in G
```

What IDs are being used in the graph? Will they match uniquely with what comes from Cube?

**Comment by josiekre** [comment]
Even more fun... we cannot use `pd.merge` if one DataFrame stores an ID as `int64` and the other as `object`. Partridge tends to choose objects for all ID fields. I think RoadwayNetwork is using ints.

**Comment by e-lo** [comment]
object is usually a string in pandas. we can force roadway network to turn
it to a  string (you can do this before a merge)

**Comment by josiekre** [comment]
@e-lo developed a new ID naming convention for RoadwayNetwork (https://github.com/wsp-sag/client_met_council_wrangler_utilities/wiki/Highway-Network). @i-am-sijia is going to update the example node table to that, and she is also going to update the sample transit network (specifically `shapes.txt`, `stops.txt`, and `stop_times.txt`) so that they both use node IDs that are internally consistent with one another. (Internal consistency for me means all stops in `stops.txt` are listed for a single trip_id in the order in `stop_times.txt` that match the trip's shape's node list in `shapes.txt`. In other words, a single node list coming from Cube like this `[235145, 1345141, -1235345, 12341234]` is put into these three files correctly.)  

I will in the meantime finish functionality for updating shapes.txt and stops.txt assuming a list of nodes comes in from the project card like this `[235145, 1345141, -1235345, 12341234]`, where the negative sign indicates a traversed node without a stop (i.e. add it to `shape.txt` but not to `stops.txt` or `stop_times.txt`). Testing will start next week Monday after a new transit network is available via @i-am-sijia. 

(cc: @DavidOry)

**Comment by josiekre** [comment]
This is a question for someone else since I do not interact with Cube, but I wanted to chime in to say that my understanding is Cube will be producing unique node IDs, not link IDs. The plan of attack above assumes node IDs.

**Comment by DavidOry** [comment]
> Does the Cube data format _have_ a unique link id?

It does not require one, as a link is uniquely defined by it's A and B pair. But it can have a link ID as another attribute, which would then require someone to maintain it. Does that help or are you after something else?

**Comment by JonathanEhrlichMC** [comment]
OK

**Comment by josiekre** [comment]
I think I have something working, where Partridge is now only used to read the GTFS files in. 

One interesting tidbit: there's a one-to-many relationship between node IDs from Cube and stop_ids from the GTFS feed. When a routing change comes in on a project card, we have node IDs. Right now, Network Wrangler randomly picks a stop_id if there is more than one stop_id's at that node. This works for now from the perspective of Met Council's model (in theory anyway), but in the long term might create funny GTFS stops sequences. Especially if a consumer of the model's GTFS downstream thinks of re-mapmatching the list of stops using the stop_id's lat/lon. In other words, we are losing information (our read/write don't produce the same thing consistently).

**Comment by josiekre** [comment]
I should specify that when more than one stop_id exists for a particular node ID, the first match in the stops.txt table is used. It is not actually random. (Remember we need a stop_id because we need it in the stop_times table, since it is a required variable there in GTFS format.) Perhaps consider departing from GTFS to solve this and going with a better-fit data format: a true ordered list (instead of sequence columns in a table).

**Comment by e-lo** [comment]
Fixed
