### ISSUE TITLE
Apply a new roadway project to a roadway network project

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#88]

**Comment by kulshresthaa** [comment]
@e-lo simple implementation for adding new links done in 4decc491004d90d4463ee1078d33fb54daf3ebda. Please review!

Questions:
* What to do if new links in the project card has fields which are not in the network? For now, I am just getting the values of fields (from project card) which are on the network and adding a new link with those values. 
* What about if not all the link fields in the network are specified in the project card for new links? Should we have a list of REQUIRED fields that needs to be included in the project card and other network fields can be optional?

**Comment by e-lo** [comment]
Looks good. I added it to the wrapper `apply` method as well.

> new links in the project card has fields which are not in the network...do we add?

Yes, we should per request from MetCouncil. This is consistent with how the update properties works now (I wrote tests to make sure, see the [two test that start here](https://github.com/wsp-sag/network_wrangler/blob/5586376fd28a866e932fbc6c403b007c0b76c6fd/tests/test_roadway.py#L259)) 

> Should we have a list of REQUIRED fields that needs to be included in the project card and other network fields can be optional?

Yes. And this should be done via the project card validation...I've created a placeholder issue #96
For your purpose right now, you don't need to worry about this.

**Comment by kulshresthaa** [comment]
@e-lo more changes done in 9da734ecac728997b7c1d6f3f719160fd0c9428a. This includes simple and mutiple roadway add and delete changes.

@i-am-sijia I have added two example project cards ([10](https://github.com/wsp-sag/network_wrangler/blob/develop/example/stpaul/project_cards/10_simple_roadway_add_change.yml) and [11](https://github.com/wsp-sag/network_wrangler/blob/develop/example/stpaul/project_cards/11_multiple_roadway_add_and_delete_change.yml)) for roadway add and delete changes. The properties and values in the cards are not correct as they are just for reference.

**Comment by kulshresthaa** [comment]
> Yes, we should per request from MetCouncil. This is consistent with how the update properties works now (I wrote tests to make sure, see the [two test that start here](https://github.com/wsp-sag/network_wrangler/blob/5586376fd28a866e932fbc6c403b007c0b76c6fd/tests/test_roadway.py#L259))

Meaning, we add all the fields (defined in the project card) to the roadway network? In the current implementation, I only bring in properties from the project card that exists on the network. Will revise it, if that's the case.

**Comment by e-lo** [comment]
Yes, please make sure those tests pass. They shouldn't pass unless you add
any non-existing fields to the network.

**Comment by kulshresthaa** [comment]
> They shouldn't pass unless you add any non-existing fields to the network.

what do you mean? now I am confused!

**Comment by kulshresthaa** [comment]
I have made the required changes to add/delete roadway features (including multiple categories of changes specified in the project card) and added some test. 

We can test it out when we have some "real" project cards to apply for add/delete. cc @i-am-sijia

**Comment by i-am-sijia** [comment]
@e-lo @arashasadabadi 

I updated project cards to match the latest examples from Ashish.  [5eec644](https://github.com/wsp-sag/network_wrangler/commit/5eec644b5ccfc7fe7091ec46d6c596d6f8d73230)

I removed AREA, COUNTY, ASGNGRP, CENTROID from project card and network standard.  And added some additional fields to network standard, e.g. T_MAINTIME, AADT per previous discussion.  Let me know otherwise.  I might have a better idea on keeping them or not when I start finalizing what fields should lasso calculate besides the 4 we discussed.

Can you also take a look at network changes and let me know if you prefer another structure?  [Especially](https://github.com/wsp-sag/network_wrangler/blob/5eec644b5ccfc7fe7091ec46d6c596d6f8d73230/example/stpaul/project_cards/wideningMinneahahaPkwy.yml#L3) when multiple links share the same changes.   Maybe something similar to addition.

**Comment by e-lo** [comment]
Thanks for updating!  A few thoughts:

1. If we use the term `travelModelId `to describe the node, should we have something similarly descriptive for link? `travel_model_linkid`?

  - Question: does Cube have a restriction on length of field names?

2. what is `T_MAINTIME`? I couldn't find it in the PRD or in the model files by doing a search via GitHub.  

3. AADT seems fine to add.

4. Can we make sure the cards include the equiv of facility type? (which we will need to calculate ASGNGRP).  This should be the [`highway` variable per OSM](https://wiki.openstreetmap.org/wiki/Key:highway)

5. Is [this ](https://github.com/wsp-sag/network_wrangler/blob/5eec644b5ccfc7fe7091ec46d6c596d6f8d73230/example/stpaul/project_cards/wideningMinneahahaPkwy.yml#L20)really right?
```
existing: 100.443968062
property: DISTANCE
set: 0.0624
```

6. Good question on multiple links. Let's loop in @kulshresthaa . I don't think it will work that way now.  In this case, it looks like it is links going in one direction and then the other.  I agree it would make sense that we should be able to make a single `facility` query and then apply the change for both.  

One easy option for this specific case would be to add a flag for `apply_to_reverse: True`

Another option would be to enable facility to be a list.  Thoughts?

**Comment by i-am-sijia** [comment]
1.  I thought of it, we can change the `LINK_ID` to `travelModelId`.  Can we use same name `travelModelId` for links?  I'm not sure if there's any drawback to use same attribute name given link and node are in separate database.

2.  I meant `T_MANTIME` (sorry about my typo in the comment), the`manually designated transit travel time` which is a manual input for rail links.  Right now it's calculated from gtfs.

4.  right, will use a default `ASGNGRP to highway cross walk` to return `highway` for roadway addition.  Shall we hold off on changed links, as most of the `ASGNGRP` is calculated based on dot data instead of OSM?

5.  network standard `DISTANCE` is in meters, while the *.log example from MetC had it in miles.  I think it's because they had lat-lon version CUBE network.  We will deliver them meter-based CUBE network `epsg 26915`, and I suppose *.log will return meters then.   We can test it later.

6.  facility as list sounds good, for 1) roadway addition also has list structure, 2) there will be cases for same changes applied to not only the reverse links, but also adjacent links.

**Comment by e-lo** [comment]
@i-am-sijia , since I think this issue is ready to be closed, I moved these conversations to other issues.

1, 2, 3: #99
5: #98
