### ISSUE TITLE
Create new node #s on the fly

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#93]
1. what does OSM do?
2. can we do it with SS?

**Comment by DavidOry** [comment]
Group discussion:

Options:
(1) SharedStreets is nice because unique (but who really cares and we'd need to bring into Lasso);
(2) We can re-number new nodes when we're done adding projects (or as we add them), might not be consistency between networks. 

Start with (2) have a fixed approach for managed lane dummy (adding a large scalar, i.e., 10000). May be good to pick a gap to a logical number (say 45,045 is the largest, use 100,000 as the first). 

What about if you build a 2040 and then a 2050, can same project have different numbers?
Best practice would be to add 2050 project cards to 2040 "base" network, which should ameliorate this. 

Comparing two build networks could be annoying with different numbers.

**Comment by DavidOry** [comment]
Cube:
* Maximum zones: 32000
* Nodes: 999,999
* Links: 999,999

**Comment by JonathanEhrlichMC** [comment]
Comparing two build networks could be annoying with different numbers. @RachelWikenMC

**Comment by e-lo** [comment]
@JonathanEhrlichMC : I agree.

**Comment by RachelWikenMC** [comment]
Absolutely agree.  need to have consistent node numbers.

**Comment by josiekre** [comment]
I agree to. I asked this during the call when we discussed. 

The ShSt "magic" is just a hash function. We should test this, but I think we could recreate the hashing function in Lasso on Intersections (i.e. nodes) without the ShSt overhead. Check out the example in the function linked below; it shows how the hashing of an Intersection works. Step 1: create a string with the same digit accuracy and smash "Intersection " at the beginning. Step 2: hash it using the same hashing function (md5). This hashing function is built in Python by someone already.

https://github.com/sharedstreets/sharedstreets-js/blob/0e6d7de0aee2e9ae3b007d1e45284b06cc241d02/src/index.ts#L553-L565

**Comment by e-lo** [comment]
Added to https://github.com/wsp-sag/client_met_council_wrangler_utilities/issues/23

**Comment by e-lo** [comment]
Right now  for the MetCouncil process we are adding any A and B nodes using Cube and the base network so I will close this issue until it becomes necessary for anybody's workflow down the road.
